#!/usr/bin/env python3
"""TrustOps pilot setup CLI — bootstrap org, clients, users, SLA, and demo data."""

import argparse
import sys
from datetime import datetime, timezone

from app.auth.security import hash_password
from app.core.constants import DEFAULT_PASSWORD, PRIORITIES, ROLES, SEVERITIES
from app.db.session import SessionLocal
from app.models import Client, Organization, Role, SLAPolicy, User, UserRole
from app.services.webhook_service import WebhookAlertService


def cmd_init_org(args):
    db = SessionLocal()
    try:
        if db.query(Organization).filter(Organization.name == args.name).first():
            print(f"Organization '{args.name}' already exists.")
            return 1
        org = Organization(name=args.name, status="active")
        db.add(org)
        db.flush()
        for role_name in ROLES:
            db.add(Role(name=role_name, description=f"{role_name} role"))
        db.commit()
        print(f"Created organization: {org.name} ({org.id})")
        return 0
    finally:
        db.close()


def cmd_add_client(args):
    db = SessionLocal()
    try:
        org = db.query(Organization).filter(Organization.name == args.org).first()
        if not org:
            print(f"Organization not found: {args.org}")
            return 1
        client = Client(
            organization_id=org.id,
            name=args.client_name,
            industry=args.industry,
            service_tier=args.tier,
        )
        db.add(client)
        db.flush()
        for severity in ("Critical", "High"):
            db.add(
                SLAPolicy(
                    client_id=client.id,
                    severity=severity,
                    time_to_triage_minutes=15 if severity == "Critical" else 30,
                    time_to_disposition_minutes=60 if severity == "Critical" else 120,
                    time_to_notify_minutes=30 if severity == "Critical" else 60,
                    time_to_close_minutes=480 if severity == "Critical" else 720,
                )
            )
        db.commit()
        print(f"Created client: {client.name} ({client.id})")
        return 0
    finally:
        db.close()


def cmd_add_user(args):
    db = SessionLocal()
    try:
        org = db.query(Organization).filter(Organization.name == args.org).first()
        if not org:
            print(f"Organization not found: {args.org}")
            return 1
        role = db.query(Role).filter(Role.name == args.role).first()
        if not role:
            print(f"Role not found: {args.role}")
            return 1
        client = None
        if args.client:
            client = db.query(Client).filter(Client.name == args.client, Client.organization_id == org.id).first()
            if not client:
                print(f"Client not found: {args.client}")
                return 1
        user = User(
            organization_id=org.id,
            client_id=client.id if client else None,
            name=args.name,
            email=args.email,
            password_hash=hash_password(args.password or DEFAULT_PASSWORD),
        )
        db.add(user)
        db.flush()
        db.add(UserRole(user_id=user.id, role_id=role.id))
        db.commit()
        print(f"Created user: {user.email} ({args.role})")
        return 0
    finally:
        db.close()


def cmd_demo_case(args):
    db = SessionLocal()
    try:
        client = db.query(Client).filter(Client.name == args.client).first()
        if not client:
            print(f"Client not found: {args.client}")
            return 1
        result = WebhookAlertService(db).ingest(
            organization_id=client.organization_id,
            client_id=client.id,
            title=args.title or "[PILOT] Demo security alert",
            severity=args.severity or "High",
            description="Generated by pilot_setup.py for demo purposes.",
            source_system=args.source or "Pilot Setup",
            priority=args.priority or "P2 High",
            detected_at=datetime.now(timezone.utc),
        )
        db.commit()
        print(f"Created demo case: {result['case_number']} ({result['case_id']})")
        return 0
    finally:
        db.close()


def cmd_full_seed(args):
    print("Running full seed (skips if database already seeded)...")
    from seed import seed

    seed()
    return 0


def main():
    parser = argparse.ArgumentParser(description="TrustOps pilot setup")
    sub = parser.add_subparsers(dest="command")

    p_org = sub.add_parser("init-org", help="Create organization and roles")
    p_org.add_argument("--name", default="TrustOps Demo SOC")
    p_org.set_defaults(func=cmd_init_org)

    p_client = sub.add_parser("add-client", help="Create client with SLA policies")
    p_client.add_argument("--org", default="TrustOps Demo SOC")
    p_client.add_argument("--client-name", required=True)
    p_client.add_argument("--industry", default="General")
    p_client.add_argument("--tier", default="Standard")
    p_client.set_defaults(func=cmd_add_client)

    p_user = sub.add_parser("add-user", help="Create user with role")
    p_user.add_argument("--org", default="TrustOps Demo SOC")
    p_user.add_argument("--email", required=True)
    p_user.add_argument("--name", required=True)
    p_user.add_argument("--role", required=True, choices=ROLES)
    p_user.add_argument("--client", default=None)
    p_user.add_argument("--password", default=None)
    p_user.set_defaults(func=cmd_add_user)

    p_case = sub.add_parser("demo-case", help="Generate a demo case via webhook ingestion")
    p_case.add_argument("--client", default="Apex Energy")
    p_case.add_argument("--title", default=None)
    p_case.add_argument("--severity", choices=SEVERITIES, default="High")
    p_case.add_argument("--priority", choices=PRIORITIES, default="P2 High")
    p_case.add_argument("--source", default="Pilot Setup")
    p_case.set_defaults(func=cmd_demo_case)

    p_seed = sub.add_parser("full-seed", help="Run full demo seed script")
    p_seed.set_defaults(func=cmd_full_seed)

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        return 1
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
